### PR TITLE
Listener is missing to register emit

### LINKED ISSUE #71: Listener is missing to register/emit events in some cases.
It was quite tricky to point down exactly when it's happening. But at times, the `listener` from `useSandpack` is failing to listen for events emitted by the sandpack bundler.
https://codesandbox.io/s/eloquent-mccarthy-qr09r?file=/src/App.tsx

STR
- Open the console and we should be able to see the logs.
- Refresh the browser or `csb` preview. And in some instances the listener won't log the events.

https://user-images.githubusercontent.com/11075561/123729554-c96bde00-d8b2-11eb-8301-8de480e06884.mov

### PR DESCRIPTION
**Pull request by danilowoz**
Basically, the main problem with not registering the listener was because the client was created after the listening has been added. So, I created a new object in the `queuedListeners` called `global`, to take care of all the events that must be added to clients, regardless of when. So I guess we cover the following cases:
 - Set a listener, but the client hasn't been created yet;
 - Set a listener, but the client has already been created;
 - A client already exists, set a new listener and then one more client has been created;

Closes #71

### CODE REVIEW

File: sandpack-react/src/contexts/sandpackContext.tsx [hunk 1]
```diff
@@ -338,7 +366,6 @@ class SandpackProvider extends React.PureComponent<
     if (client) {
       client.cleanup();
       delete this.clients[clientId];
-      delete this.unsubscribeQueuedListeners[clientId];
```
Comment (danilowoz) [inline sandpack-react/src/contexts/sandpackContext.tsx:341]: This was causing the main error when unmounting a client. So, I think we can remove this at all since unsubscription functions need to handle the entire list before cleaning themselves from this list.

File: sandpack-react/src/contexts/sandpackContext.tsx [hunk 2]
```diff
@@ -313,6 +326,21 @@ class SandpackProvider extends React.PureComponent<
       this.queuedListeners[clientId] = {};
     }
 
+    /**
+     * Register global listeners
+     */
+    const globalListeners = Object.entries(this.queuedListeners.global);
```
Comment (alexnm) [inline sandpack-react/src/contexts/sandpackContext.tsx:332]: This is a good catch, and I like the approach

File: sandpack-react/src/contexts/sandpackContext.tsx [hunk 3]
```diff
@@ -394,7 +423,8 @@ class SandpackProvider extends React.PureComponent<
           this.unsubscribeQueuedListeners[clientId] || {};
 
         this.queuedListeners[clientId][listenerId] = listener;
-        return () => {
+
+        const unsubscribeListener = () => {
```
Comment (alexnm) [inline sandpack-react/src/contexts/sandpackContext.tsx:427]: Question: Is this useful for debugging or why is the change needed?

File: sandpack-react/src/contexts/sandpackContext.tsx (hunk 1 above)
Comment (alexnm) [reply sandpack-react/src/contexts/sandpackContext.tsx:341]: Yes, this is a bit over-optimized, the important thing is that the unsubscribe functions get called. `this.unsubscribeQueuedListeners[clientId]` would not be used after this if block executes

File: sandpack-react/src/contexts/sandpackContext.tsx [hunk 4]
```diff
@@ -406,12 +436,37 @@ class SandpackProvider extends React.PureComponent<
...
       }
     } else {
-      const unsubs = Object.values(this.clients).map((client) =>
+      // Push to the **global** queue
+      const listenerId = generateRandomId();
+      this.queuedListeners.global[listenerId] = listener;
+
+      // Add to the current clients
+      const clients = Object.values(this.clients);
+      const currentClientListeners = clients.map((client) =>
```
Comment (alexnm) [inline sandpack-react/src/contexts/sandpackContext.tsx:449]: nitpick: I would rename this to currentClientUnsubscribeListeners, for clarity

File: sandpack-react/src/contexts/sandpackContext.tsx [hunk 5]
```diff
@@ -406,12 +436,37 @@ class SandpackProvider extends React.PureComponent<
...
+      const currentClientListenersUnsubscribe = () => {
+        currentClientListeners.forEach((unsubscribe) => unsubscribe());
+      };
+
+      const unsubscribeListener = () => {
+        const unsubscribeQueuedClients = Object.values(
+          this.unsubscribeQueuedListeners
+        );
+
+        unsubscribeQueuedClients.forEach((listenerOfClient) => {
```
Comment (alexnm) [inline sandpack-react/src/contexts/sandpackContext.tsx:461]: Can you leave a comment for this block as well? I believe it is unsubscribing the listeners which were initially queued globally and were added to each unsubscribeQueuedListeners[clientId], right?

File: sandpack-react/src/contexts/sandpackContext.tsx [hunk 6]
```diff
@@ -406,12 +436,37 @@ class SandpackProvider extends React.PureComponent<
...
+      const listenerId = generateRandomId();
+      this.queuedListeners.global[listenerId] = listener;
+
+      // Add to the current clients
+      const clients = Object.values(this.clients);
+      const currentClientListeners = clients.map((client) =>
         client.listen(listener)
       );
-      return () => unsubs.forEach((unsub) => unsub());
+      const currentClientListenersUnsubscribe = () => {
```
Comment (alexnm) [inline sandpack-react/src/contexts/sandpackContext.tsx:452]: nitpick: because there are already a bunch of functions/variables here with similar names, I would keep this as an anonymous function at line 466, because it is similar with the other foreach that unsubscribes from each "future" client. Also, `current` might be misleading in the name, since timeline is super complex in this function :)

**Review by alexnm — APPROVED** [review]
Really great job @danilowoz, this has to be the most complicated flow in the entire library and you found the issue with ease.

File: sandpack-react/src/contexts/sandpackContext.tsx (hunk 1 above)
Comment (danilowoz) [reply sandpack-react/src/contexts/sandpackContext.tsx:341]: Yeah, I wouldn't worry about this extra optimization, because the object will be empty at the end of unsubscribing listener process.

File: sandpack-react/src/contexts/sandpackContext.tsx (hunk 3 above)
Comment (danilowoz) [reply sandpack-react/src/contexts/sandpackContext.tsx:427]: I did it just to make the code clearer, now each conditional returns the same kind of function and which makes it easy to read long complex parts of code.

**Review by alexnm — APPROVED** [review]
